# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bovada_password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bovada_username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
