# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20160113_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BovadaAccounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiles.BovadaProfile'),
        ),
    ]
