# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_profile_bovadaaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovadaprofile',
            name='checked_for_validity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bovadaprofile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
