# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=250)),
                ('away_team', models.CharField(max_length=250)),
                ('sport', models.CharField(max_length=250)),
                ('odds_type', models.IntegerField(blank=True, null=True)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('handicap', models.FloatField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bovadabet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Streamer.Bet')),
                ('match_id', models.IntegerField(blank=True, null=True)),
                ('outcome_id', models.IntegerField(blank=True, null=True)),
                ('price_id', models.IntegerField(blank=True, null=True)),
            ],
            bases=('Streamer.bet',),
        ),
        migrations.CreateModel(
            name='Edgebet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Streamer.Bet')),
                ('edgebet_id', models.IntegerField(blank=True, null=True)),
                ('edge', models.FloatField(blank=True, null=True)),
            ],
            bases=('Streamer.bet',),
        ),
    ]
