# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0002_auto_20151214_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgebet',
            old_name='recieved',
            new_name='recieved_date',
        ),
    ]
