# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0003_auto_20151214_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovadabet',
            name='match_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
