# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0005_auto_20151215_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
