# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0006_bet_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastfetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_fetch', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
