# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0008_auto_20151216_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fetches',
            new_name='Fetchhistory',
        ),
        migrations.RenameField(
            model_name='fetchhistory',
            old_name='time_of_fetch',
            new_name='time',
        ),
    ]
