# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0011_auto_20151218_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='is_win',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='stake',
        ),
        migrations.RemoveField(
            model_name='edgebet',
            name='recieved_date',
        ),
        migrations.RemoveField(
            model_name='edgebet',
            name='sibling',
        ),
        migrations.AddField(
            model_name='bet',
            name='recieved_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='away_team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='home_team',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odds_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='outcome_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='sport',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bovadabet',
            name='match_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
