# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0012_auto_20151218_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='stake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
