# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0013_auto_20151218_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgebet',
            name='sibling',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Streamer.Bovadabet'),
        ),
    ]
