# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0014_edgebet_sibling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgebet',
            name='sibling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Streamer.Bovadabet'),
        ),
    ]
