# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0015_auto_20151218_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='odds_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
