# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0016_auto_20151221_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
