# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streamer', '0017_bet_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
